language: python

# use container-based infrastructure
sudo : false
dist: trusty

python:
  - "3.6"

branches:
  only:
    - master

env:
  - PINT="N" PYVISA='N'
  - PINT="Y" PYVISA='Y'

before_install:
  - REDIRECT_TO=/dev/stdout  # change to /dev/null to silence Travis
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/anaconda &> ${REDIRECT_TO}
  - export PATH=~/anaconda/bin:$PATH
  - conda update --yes --quiet conda &> ${REDIRECT_TO}

  - SRC_DIR=$(pwd)
  - export ENV_NAME=travis

install:
  - conda create --yes -n $ENV_NAME python=$TRAVIS_PYTHON_VERSION pip > ${REDIRECT_TO};
  - source activate $ENV_NAME
  - conda install --yes --quiet pytest> ${REDIRECT_TO};
  - pip install -q pytest-cov pytest-catchlog stringparser
  # Use develop version of Pint
  - if [ $PINT == 'Y' ]; then pip install https://github.com/hgrecco/pint/zipball/develop; fi
  # Use develop version of pyvisa
  - if [ $PYVISA == 'Y' ]; then pip install -q https://github.com/hgrecco/pyvisa/zipball/master; fi
  - pip install -q codecov

script:
  - cd ${SRC_DIR}
  - py.test tests/core -v --cov i3py.core --cov-report xml

after_script:
  - codecov
